name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Add safe directory
      run: git config --global --add safe.directory /github/workspace

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Setup Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install --jobs=4 --retry=3
      working-directory: .

    - name: Build the Jekyll site
      run: bundle exec jekyll build
      working-directory: .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

    - name: Update Algolia index (optional)
      run: bundle exec jekyll algolia push
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      continue-on-error: true
